### ISSUE TITLE
Please, make a version tags

### ISSUE THREAD

**Issue by KIVagant** [muriloacs/Middleware#2]
```
composer require muriloamaral/middleware

> Could not find package muriloamaral/middleware at any version for your minimum-stability (stable).
```

It is not really safe to add requirements from master branch.

**Comment by edipoReboucas** [comment]
@muriloacs the current code is good enough to close a release? We can use semantic version: http://semver.org/

**Comment by muriloacs** [comment]
I think so :)

**Comment by edipoReboucas** [comment]
https://github.com/muriloacs/Middleware/tree/v1.0.0
Done.

**Comment by KIVagant** [comment]
It seems like you forgot to update the package on packagist:
https://packagist.org/packages/muriloamaral/middleware

There are still no versions available.

**Comment by KIVagant** [comment]
I think, the Packagist prefer version names without 'v' prefix, e.g. '1.0.0' but not 'v1.0.0'

**Comment by edipoReboucas** [comment]
Please @muriloacs, update the packagist.

**Comment by muriloacs** [comment]
Packagist is up to date.

**Comment by KIVagant** [comment]
@muriloacs, JFYI: I recommend to add "license" property to composer.json
